// Code generated by protoc-gen-go. DO NOT EDIT.
// source: judgemessage.proto

package protofile

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnumMessageCommand int32

const (
	EnumMessageCommand_enumJudgeRequest     EnumMessageCommand = 0
	EnumMessageCommand_enumJudgeRresponse   EnumMessageCommand = 1
	EnumMessageCommand_enumQueryRequest     EnumMessageCommand = 2
	EnumMessageCommand_enumQueryResponse    EnumMessageCommand = 3
	EnumMessageCommand_enumQueryAllRequest  EnumMessageCommand = 4
	EnumMessageCommand_enumQueryAllResponse EnumMessageCommand = 5
)

var EnumMessageCommand_name = map[int32]string{
	0: "enumJudgeRequest",
	1: "enumJudgeRresponse",
	2: "enumQueryRequest",
	3: "enumQueryResponse",
	4: "enumQueryAllRequest",
	5: "enumQueryAllResponse",
}

var EnumMessageCommand_value = map[string]int32{
	"enumJudgeRequest":     0,
	"enumJudgeRresponse":   1,
	"enumQueryRequest":     2,
	"enumQueryResponse":    3,
	"enumQueryAllRequest":  4,
	"enumQueryAllResponse": 5,
}

func (x EnumMessageCommand) String() string {
	return proto.EnumName(EnumMessageCommand_name, int32(x))
}

func (EnumMessageCommand) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db388fc8428a9d14, []int{0}
}

type Packet struct {
	Version              int32              `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Command              EnumMessageCommand `protobuf:"varint,2,opt,name=command,proto3,enum=protofile.EnumMessageCommand" json:"command,omitempty"`
	Userid               int32              `protobuf:"varint,3,opt,name=userid,proto3" json:"userid,omitempty"`
	Serialized           []byte             `protobuf:"bytes,4,opt,name=serialized,proto3" json:"serialized,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_db388fc8428a9d14, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Packet) GetCommand() EnumMessageCommand {
	if m != nil {
		return m.Command
	}
	return EnumMessageCommand_enumJudgeRequest
}

func (m *Packet) GetUserid() int32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *Packet) GetSerialized() []byte {
	if m != nil {
		return m.Serialized
	}
	return nil
}

type JudgeRequest struct {
	ProblemId            int32    `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	UserCode             string   `protobuf:"bytes,2,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JudgeRequest) Reset()         { *m = JudgeRequest{} }
func (m *JudgeRequest) String() string { return proto.CompactTextString(m) }
func (*JudgeRequest) ProtoMessage()    {}
func (*JudgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db388fc8428a9d14, []int{1}
}

func (m *JudgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeRequest.Unmarshal(m, b)
}
func (m *JudgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeRequest.Marshal(b, m, deterministic)
}
func (m *JudgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeRequest.Merge(m, src)
}
func (m *JudgeRequest) XXX_Size() int {
	return xxx_messageInfo_JudgeRequest.Size(m)
}
func (m *JudgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeRequest proto.InternalMessageInfo

func (m *JudgeRequest) GetProblemId() int32 {
	if m != nil {
		return m.ProblemId
	}
	return 0
}

func (m *JudgeRequest) GetUserCode() string {
	if m != nil {
		return m.UserCode
	}
	return ""
}

type QueryRequest struct {
	ProblemId            int32    `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db388fc8428a9d14, []int{2}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetProblemId() int32 {
	if m != nil {
		return m.ProblemId
	}
	return 0
}

type JudgeResponse struct {
	ProblemId            int32    `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	JudgeSol             int32    `protobuf:"varint,2,opt,name=judge_sol,json=judgeSol,proto3" json:"judge_sol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JudgeResponse) Reset()         { *m = JudgeResponse{} }
func (m *JudgeResponse) String() string { return proto.CompactTextString(m) }
func (*JudgeResponse) ProtoMessage()    {}
func (*JudgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db388fc8428a9d14, []int{3}
}

func (m *JudgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeResponse.Unmarshal(m, b)
}
func (m *JudgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeResponse.Marshal(b, m, deterministic)
}
func (m *JudgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeResponse.Merge(m, src)
}
func (m *JudgeResponse) XXX_Size() int {
	return xxx_messageInfo_JudgeResponse.Size(m)
}
func (m *JudgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeResponse proto.InternalMessageInfo

func (m *JudgeResponse) GetProblemId() int32 {
	if m != nil {
		return m.ProblemId
	}
	return 0
}

func (m *JudgeResponse) GetJudgeSol() int32 {
	if m != nil {
		return m.JudgeSol
	}
	return 0
}

type QueryResponse struct {
	ProblemId            int32    `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	ProblemTitle         string   `protobuf:"bytes,2,opt,name=problem_title,json=problemTitle,proto3" json:"problem_title,omitempty"`
	ProblemDes           string   `protobuf:"bytes,3,opt,name=problem_des,json=problemDes,proto3" json:"problem_des,omitempty"`
	ProblemSampleIn      string   `protobuf:"bytes,4,opt,name=problem_sample_in,json=problemSampleIn,proto3" json:"problem_sample_in,omitempty"`
	ProblemSampleOut     string   `protobuf:"bytes,5,opt,name=problem_sample_out,json=problemSampleOut,proto3" json:"problem_sample_out,omitempty"`
	ProblemTime          int32    `protobuf:"varint,6,opt,name=problem_time,json=problemTime,proto3" json:"problem_time,omitempty"`
	ProblemMem           int32    `protobuf:"varint,7,opt,name=problem_mem,json=problemMem,proto3" json:"problem_mem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db388fc8428a9d14, []int{4}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetProblemId() int32 {
	if m != nil {
		return m.ProblemId
	}
	return 0
}

func (m *QueryResponse) GetProblemTitle() string {
	if m != nil {
		return m.ProblemTitle
	}
	return ""
}

func (m *QueryResponse) GetProblemDes() string {
	if m != nil {
		return m.ProblemDes
	}
	return ""
}

func (m *QueryResponse) GetProblemSampleIn() string {
	if m != nil {
		return m.ProblemSampleIn
	}
	return ""
}

func (m *QueryResponse) GetProblemSampleOut() string {
	if m != nil {
		return m.ProblemSampleOut
	}
	return ""
}

func (m *QueryResponse) GetProblemTime() int32 {
	if m != nil {
		return m.ProblemTime
	}
	return 0
}

func (m *QueryResponse) GetProblemMem() int32 {
	if m != nil {
		return m.ProblemMem
	}
	return 0
}

type QueryAllResponse struct {
	ProblemList          []*QueryResponse `protobuf:"bytes,1,rep,name=problem_list,json=problemList,proto3" json:"problem_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *QueryAllResponse) Reset()         { *m = QueryAllResponse{} }
func (m *QueryAllResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllResponse) ProtoMessage()    {}
func (*QueryAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db388fc8428a9d14, []int{5}
}

func (m *QueryAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAllResponse.Unmarshal(m, b)
}
func (m *QueryAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAllResponse.Marshal(b, m, deterministic)
}
func (m *QueryAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllResponse.Merge(m, src)
}
func (m *QueryAllResponse) XXX_Size() int {
	return xxx_messageInfo_QueryAllResponse.Size(m)
}
func (m *QueryAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllResponse proto.InternalMessageInfo

func (m *QueryAllResponse) GetProblemList() []*QueryResponse {
	if m != nil {
		return m.ProblemList
	}
	return nil
}

func init() {
	proto.RegisterEnum("protofile.EnumMessageCommand", EnumMessageCommand_name, EnumMessageCommand_value)
	proto.RegisterType((*Packet)(nil), "protofile.Packet")
	proto.RegisterType((*JudgeRequest)(nil), "protofile.JudgeRequest")
	proto.RegisterType((*QueryRequest)(nil), "protofile.QueryRequest")
	proto.RegisterType((*JudgeResponse)(nil), "protofile.JudgeResponse")
	proto.RegisterType((*QueryResponse)(nil), "protofile.QueryResponse")
	proto.RegisterType((*QueryAllResponse)(nil), "protofile.QueryAllResponse")
}

func init() { proto.RegisterFile("judgemessage.proto", fileDescriptor_db388fc8428a9d14) }

var fileDescriptor_db388fc8428a9d14 = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x6e, 0xd3, 0x4e,
	0x10, 0xc6, 0xff, 0x4e, 0x9a, 0xa4, 0x9e, 0x38, 0x7f, 0xdc, 0xa1, 0x94, 0x95, 0x50, 0x21, 0x98,
	0x4b, 0x54, 0x41, 0x0e, 0xe5, 0xc0, 0x81, 0x13, 0x2a, 0x1c, 0x5a, 0xa8, 0x0a, 0x2e, 0xf7, 0xc8,
	0xcd, 0x0e, 0xd5, 0xc2, 0xae, 0x37, 0x78, 0xd7, 0x48, 0xf0, 0x18, 0xf0, 0x06, 0x3c, 0x29, 0xf2,
	0x66, 0xd7, 0x71, 0xe0, 0x92, 0x53, 0xb2, 0xdf, 0xfc, 0xfc, 0xcd, 0x37, 0xa3, 0x01, 0xfc, 0x5c,
	0xf3, 0x5b, 0x52, 0x64, 0x4c, 0x71, 0x4b, 0xf3, 0x55, 0xa5, 0xad, 0xc6, 0xd8, 0xfd, 0x7c, 0x12,
	0x92, 0xb2, 0x5f, 0x11, 0x0c, 0xdf, 0x17, 0xcb, 0x2f, 0x64, 0x91, 0xc1, 0xe8, 0x1b, 0x55, 0x46,
	0xe8, 0x92, 0x45, 0xd3, 0x68, 0x36, 0xc8, 0xc3, 0x13, 0x5f, 0xc0, 0x68, 0xa9, 0x95, 0x2a, 0x4a,
	0xce, 0x7a, 0xd3, 0x68, 0xf6, 0xff, 0xe9, 0xf1, 0xbc, 0x75, 0x98, 0xbf, 0x29, 0x6b, 0x75, 0xb9,
	0xb6, 0x3f, 0x5b, 0x43, 0x79, 0xa0, 0xf1, 0x08, 0x86, 0xb5, 0xa1, 0x4a, 0x70, 0xd6, 0x77, 0x8e,
	0xfe, 0x85, 0x0f, 0x01, 0x9a, 0x3f, 0x85, 0x14, 0x3f, 0x88, 0xb3, 0xbd, 0x69, 0x34, 0x4b, 0xf2,
	0x8e, 0x92, 0x5d, 0x40, 0x72, 0xd1, 0xc4, 0xce, 0xe9, 0x6b, 0x4d, 0xc6, 0xe2, 0x31, 0xc0, 0xaa,
	0xd2, 0x37, 0x92, 0xd4, 0x42, 0x70, 0x9f, 0x2e, 0xf6, 0xca, 0x39, 0xc7, 0x07, 0x10, 0x37, 0xc6,
	0x8b, 0xa5, 0xe6, 0xe4, 0x12, 0xc6, 0xf9, 0x7e, 0x23, 0x9c, 0x69, 0x4e, 0xd9, 0x33, 0x48, 0x3e,
	0xd4, 0x54, 0x7d, 0xdf, 0xcd, 0x2b, 0x7b, 0x0b, 0x13, 0xdf, 0xda, 0xac, 0x74, 0x69, 0x68, 0x87,
	0xde, 0x6e, 0xc3, 0x0b, 0xa3, 0xa5, 0xeb, 0x3d, 0xc8, 0xf7, 0x9d, 0x70, 0xad, 0x65, 0xf6, 0xb3,
	0x07, 0x13, 0xdf, 0x7c, 0x37, 0xb7, 0x27, 0x30, 0x09, 0x65, 0x2b, 0xac, 0x0c, 0xd3, 0x24, 0x5e,
	0xfc, 0xd8, 0x68, 0xf8, 0x08, 0xc6, 0x01, 0xe2, 0x64, 0xdc, 0x6a, 0xe3, 0x3c, 0xd8, 0xbe, 0x26,
	0x83, 0x27, 0x70, 0x10, 0x00, 0x53, 0xa8, 0x95, 0xa4, 0x85, 0x28, 0xdd, 0x96, 0xe3, 0xfc, 0x8e,
	0x2f, 0x5c, 0x3b, 0xfd, 0xbc, 0xc4, 0xa7, 0x80, 0x7f, 0xb1, 0xba, 0xb6, 0x6c, 0xe0, 0xe0, 0x74,
	0x0b, 0xbe, 0xaa, 0x2d, 0x3e, 0x86, 0x64, 0x93, 0x4f, 0x11, 0x1b, 0xba, 0x01, 0xc6, 0x6d, 0x3c,
	0xb5, 0x95, 0x4e, 0x91, 0x62, 0x23, 0x47, 0x84, 0x74, 0x97, 0xa4, 0xb2, 0x2b, 0x48, 0xdd, 0x4e,
	0x5e, 0x49, 0xd9, 0xae, 0xe5, 0xe5, 0xc6, 0x57, 0x0a, 0x63, 0x59, 0x34, 0xed, 0xcf, 0xc6, 0xa7,
	0xac, 0x73, 0x66, 0x5b, 0x6b, 0x6c, 0x3b, 0xbe, 0x13, 0xc6, 0x9e, 0xfc, 0x8e, 0x00, 0xff, 0xbd,
	0x42, 0x3c, 0x84, 0x94, 0xca, 0x5a, 0x75, 0x0f, 0x29, 0xfd, 0x0f, 0x8f, 0x00, 0x37, 0x6a, 0xe5,
	0xfd, 0xd2, 0x28, 0xd0, 0xdd, 0x53, 0x49, 0x7b, 0x78, 0x0f, 0x0e, 0x3a, 0xaa, 0x87, 0xfb, 0x78,
	0x1f, 0xee, 0xb6, 0xb2, 0x1b, 0x63, 0xcd, 0xef, 0x21, 0x83, 0xc3, 0xed, 0x82, 0xff, 0x64, 0x70,
	0x33, 0x74, 0xa3, 0x3c, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x29, 0x15, 0x88, 0x85, 0x90, 0x03,
	0x00, 0x00,
}
